### ISSUE TITLE
canal binlog 丢失

### ISSUE THREAD

**Issue by xiaopan0513** [alibaba/canal#425]
现网数据变更较大，发现数据存在遗漏的情况，定位在binlog未接收到事件信息。

对比发现binlog 29827255 未知的信息丢失

dump binlog
![image](https://user-images.githubusercontent.com/8357717/33230017-72c7cf0e-d1a0-11e7-94e6-981ab2367e25.png)

canal log
![image](https://user-images.githubusercontent.com/8357717/33230032-0865fa2c-d1a1-11e7-90ae-a62fc76fbbe5.png)

**Comment by xiaopan0513** [comment]
![image](https://user-images.githubusercontent.com/8357717/33230062-a4101d04-d1a1-11e7-83d1-c151ca6b771f.png)

日志丢失的问题看源码找到原因了，但是binlog接收处确实未接收到，log每次会将接收到的binlog打印出来，29827255未被接收，处理代码如下

```

void execute() {
        long batchId;
        LOGGER.debug("execute destination : " + destination);
        while (true) {
            try {
                connector.connect();
                connector.subscribe(filter);
                while (true) {
                    Message message = connector.getWithoutAck(BATCH_SIZE);
                    batchId = message.getId();
                    int size = message.getEntries().size();
                    if (batchId == -1 || size == 0) {
                        try {
                            Thread.sleep(SLEEP_TIME);
                        } catch (InterruptedException ignored) {
                            // ignored
                        }
                    } else {
                        process(message.getEntries());
                    }
                    connector.ack(batchId);
                }
            } catch (Exception e) {
                LOGGER.error("canal connect error, destination : " + destination, e);
                AlarmUtil.dcAlarm(App.DC_ID, "canal_connect_error",
                        "canal connect error, destination : " + destination);
            } finally {
                connector.disconnect();
            }

            try {
                Thread.sleep(1000 * 60);
            } catch (InterruptedException e) {
                // ignored
            }
        }
    }


    private void process(List<CanalEntry.Entry> entryList) {
        for (CanalEntry.Entry entry : entryList) {
            if (entry.getEntryType() == CanalEntry.EntryType.TRANSACTIONBEGIN
                    || entry.getEntryType() == CanalEntry.EntryType.TRANSACTIONEND) {
                continue;
            }

            if (entry.getEntryType() != CanalEntry.EntryType.ROWDATA) {
                continue;
            }

            CanalEntry.RowChange rowChange;
            try {
                rowChange = CanalEntry.RowChange.parseFrom(entry.getStoreValue());
            } catch (Exception e) {
                throw new RuntimeException("parse event has an error , data:" + entry.toString(), e);
            }

            CanalEntry.EventType eventType = rowChange.getEventType();
            if (eventType == CanalEntry.EventType.DELETE) {
                return;
            }

            if (eventType != CanalEntry.EventType.INSERT && eventType != CanalEntry.EventType.UPDATE) {
                return;
            }

            List<CanalEntry.RowData> rowDataList = rowChange.getRowDatasList();
            if (rowDataList == null || rowDataList.size() == 0) {
                continue;
            }

            List<BinlogColumnDTO> columns = new ArrayList<>();
            try {
                for (CanalEntry.RowData rowData : rowDataList) {
                    columns = convertColumnList(rowData.getAfterColumnsList());
                    long updatedCount = columns.stream().filter(BinlogColumnDTO::getUpdated).count();
                    if (updatedCount < 1) {
                        return;
                    }

                    String binlogFileOffset = entry.getHeader().getLogfileName() + ":"
                            + entry.getHeader().getLogfileOffset() + ":"
                            + DateUtil.timestamp2DateTime(entry.getHeader().getExecuteTime());

                    LOGGER.log(ACCESS, binlogFileOffset + ", eventType : {}, data : {}",
                            eventType, toJsonString(columns));

                    if (eventType == CanalEntry.EventType.INSERT) {
                        syncService.insert(columns, binlogFileOffset);
                    }
                    else if (eventType == CanalEntry.EventType.UPDATE){
                        syncService.update(columns, binlogFileOffset);
                    }
                }
            }
            catch (Exception e) {
                LOGGER.error("binlog handle error, data : " + JSONArray.toJSONString(columns), e);
                AlarmUtil.dcAlarm(App.DC_ID, "binlog_handle_error", e.toString());
            }

        }
    }

```

**Comment by xiaopan0513** [comment]
跟踪源码，canal server打印debug日志，发现client发请求过来的时候是有读取到对应postion的，但就是没有返回事件内容过去。

另一个案例的截图 

binlog file

![image](https://user-images.githubusercontent.com/8357717/33230711-53efdf28-d1ae-11e7-87ac-229d440857f0.png)

canal server log
![image](https://user-images.githubusercontent.com/8357717/33230713-6129ee18-d1ae-11e7-899c-58cdc8d1e51c.png)

**Comment by agapple** [comment]
1.  你这最后的日志是在位点定位的时候得，不是数据读取的日志
2.  canal log里记录的位点是以批次为单位，并没有精确到一条记录.  

确认过滤条件没问题吧？

**Comment by xiaopan0513** [comment]
只过滤了一个表，如果是过滤条件的问题，那应该一条记录都获取不到啊，目前的情况时部分binlog丢失

instance.properties
# table regex
canal.instance.filter.regex = p2p.t_loan
# table black regex
canal.instance.filter.black.regex =

**Comment by xiaopan0513** [comment]
传递的filter：p2p.t_loan

**Comment by JasonHuangHuster** [comment]
有结论吗？我这边最新版26也发现更新记录有丢失的问题。

**Comment by xesygao** [comment]
@JasonHuangHuster 请问解决了么，我1.1.0也出现1000条数据丢一两条的问题

**Comment by agapple** [comment]
建议你们先用标准的example工程打印接收到的数据，如果有能复现的方式最好能提供一下

**Comment by geyuandong** [comment]
有解决吗？我这边也遇到binlog丢失的情况

**Comment by geyuandong** [comment]
我用的是canal-1.0.24，数据库用的是MariaDB 10.1.19

**Comment by xesygao** [comment]
@agapple 我发现当数据丢失的时候，canal日志会报解析异常
这是错误日志：
2018-09-12 17:08:12.989 [New I/O server worker #1-7] INFO  c.a.otter.canal.instance.core.AbstractCan
alInstance - subscribe filter change to immig([1-8]|1[0-8])\.immig_enc_text
2018-09-12 17:09:37.077 [destination = IMMIG_200 , address = /172.16.40.200:3306 , EventParser] ERRO
R c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address 172.16.40.200/172.16.40.200:3
306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception
.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[na:1.8.0_171]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[na:1.8.0_171]
	at com.alibaba.otter.canal.parse.driver.mysql.packets.UUIDSet.toString(UUIDSet.java:125) ~[c
anal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.packets.MysqlGTIDSet.toString(MysqlGTIDSet.jav
a:111) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.createHeader(LogEventC
onvert.java:849) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEven
tConvert.java:561) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onE
vent(MysqlMultiStageCoprocessor.java:302) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onE
vent(MysqlMultiStageCoprocessor.java:288) ~[canal.parse-1.1.0.jar:na]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.
0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.
0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-09-12 17:09:37.078 [destination = IMMIG_200 , address = /172.16.40.200:3306 , EventParser] ERRO
R com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:IMMIG_200[com.alibaba.otter.can
al.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException:
 parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at com.alibaba.otter.canal.parse.driver.mysql.packets.UUIDSet.toString(UUIDSet.java:125)
	at com.alibaba.otter.canal.parse.driver.mysql.packets.MysqlGTIDSet.toString(MysqlGTIDSet.jav
a:111)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.createHeader(LogEventC
onvert.java:849)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEven
tConvert.java:561)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onE
vent(MysqlMultiStageCoprocessor.java:302)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onE
vent(MysqlMultiStageCoprocessor.java:288)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]
2018-09-12 17:09:51.781 [destination = IMMIG_200 , address = /172.16.40.200:3306 , EventParser] WARN
  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - find start position : EntryPosition[includ
ed=false,journalName=mysql-bin.000012,position=46893782,serverId=200,gtid=85506e6a-a0f8-11e8-96b3-00
5056b70bff:1-85344,timestamp=1536743377000]
2018-09-12 17:09:53.682 [New I/O server worker #1-9] INFO  c.a.otter.canal.instance.core.AbstractCan
alInstance - subscribe filter change to immig([1-8]|1[0-8])\.immig_enc_text

这是我的binlog：（4757那条是丢失的）
### INSERT INTO `immig2`.`immig_enc_text`
### SET
###   @1='4756'
###   @2='Name-20180912171327-3073F1CC4D611dd0b13565e94969af0b4fe0972d58bf'
###   @3='DETAIL-20180912171327-73F1CC4D611dd0b13565e94969af0b4fe0972d58bf'
###   @4='BIRTHDATE-20180912171327-1CC4D611dd0b13565e94969af0b4fe0972d58bf'
###   @5='1dd0b13565e94969af0b4fe0972d58bf'
###   @6='1'
###   @7='00'
###   @8='1'
###   @9='1'
###   @10='20180912171327'
###   @11='CHN'
###   @12=1536743376
# at 46871947
#180912 17:09:36 server id 200  end_log_pos 46872041 CRC32 0xf43de30e 	Table_map: `immig2`.`immig_enc_text` mapped to number 111
# at 46872041
#180912 17:09:36 server id 200  end_log_pos 46872344 CRC32 0x32dac44c 	Write_rows: table id 111 flags: STMT_END_F
### INSERT INTO `immig2`.`immig_enc_text`
### SET
###   @1='4757'
###   @2='Name-20180912171327-3073F1CC4D615b1e326471284984b522636e96b55fc3'
###   @3='DETAIL-20180912171327-73F1CC4D615b1e326471284984b522636e96b55fc3'
###   @4='BIRTHDATE-20180912171327-1CC4D615b1e326471284984b522636e96b55fc3'
###   @5='5b1e326471284984b522636e96b55fc3'
###   @6='1'
###   @7='00'
###   @8='1'
###   @9='1'
###   @10='20180912171327'
###   @11='CHN'
###   @12=1536743376
# at 46872344
#180912 17:09:36 server id 200  end_log_pos 46872438 CRC32 0x4dd666d7 	Table_map: `immig2`.`immig_enc_text` mapped to number 111
# at 46872438
#180912 17:09:36 server id 200  end_log_pos 46872741 CRC32 0x86092308 	Write_rows: table id 111 flags: STMT_END_F
### INSERT INTO `immig2`.`immig_enc_text`
### SET
###   @1='4758'
###   @2='Name-20180912171327-3073F1CC4D618b85988e6a054822800bf861691f6e13'
###   @3='DETAIL-20180912171327-73F1CC4D618b85988e6a054822800bf861691f6e13'
###   @4='BIRTHDATE-20180912171327-1CC4D618b85988e6a054822800bf861691f6e13'
###   @5='8b85988e6a054822800bf861691f6e13'
###   @6='1'
###   @7='00'
###   @8='1'
###   @9='1'
###   @10='20180912171327'
###   @11='CHN'
###   @12=1536743376
# at 46872741
#180912 17:09:36 server id 200  end_log_pos 46872835 CRC32 0xeb520dc4 	Table_map: `immig2`.`immig_enc_text` mapped to number 111
# at 46872835
#180912 17:09:36 server id 200  end_log_pos 46873138 CRC32 0x31e40985 	Write_rows: table id 111 flags: STMT_END_F

**Comment by lcybo** [comment]
@xesygao
ConcurrentModificationException的问题:
https://github.com/alibaba/canal/pull/902

**Comment by xesygao** [comment]
@lcybo 由于串行的性能对我来说已经够用了，我暂时先用串行解析，测试了十几次没出现丢数据的问题了。tks
